import re

instruction_table = {
	'addiu' : ['0x09','rs','rt','imm'],
	'addu'  : ['0x00','rs','rt','rd','shamt','0x21'],
	'and'   : ['0x00','rs','rt','rd','shamt','0x24'],
	'andi'  : ['0x0C','rs','rt','imm'],
	'beq'   : ['0x04','rs','rt','imm'],
    'bgez'  : ['0x01','rs','rt','imm'],
    'bgezal': ['0x01','rs','rt','imm'],
    'bgtz'  : ['0x07','rs','rt','imm'],
    'blez'  : ['0x06','rs','rt','imm'],
    'bltz'  : ['0x01','rs','rt','imm'],
    'bltzal': ['0x01','rs','rt','imm'],
	'bne'   : ['0x05','rs','rt','imm'],
	'div'   : ['0x00','rs','rt','rd','shamt','0x1A'],
	'divu'  : ['0x00','rs','rt','rd','shamt','0x1B'],
    'j'     : ['0x02', 'add'],
    'jalr'  : ['0x00','rs','rt','rd','shamt','0x09'],
	'jal'   : ['0x03', 'add'],
	'jr'    : ['0x00','rs','rt','rd','shamt','0x08'],
    'lb'    : ['0x20','rs','rt','imm'],
	'lbu'   : ['0x24','rs','rt','imm'],
    'lh'    : ['0x21','rs','rt','imm'],
	'lhu'   : ['0x25','rs','rt','imm'],
	'lui'   : ['0x0F','rs','rt','imm'],
	'lw'    : ['0x23','rs','rt','imm'],
    'lwl'   : ['0x22','rs','rt','imm'],
    'lwr'   : ['0x26','rs','rt','imm'],
    'mthi'  : ['0x00','rs','rt','rd','shamt','0x11'],
    'mtlo'  : ['0x00','rs','rt','rd','shamt','0x13'],
    'mult'  : ['0x00','rs','rt','rd','shamt','0x18'],
    'multu' : ['0x00','rs','rt','rd','shamt','0x19'],
	'or'    : ['0x00','rs','rt','rd','shamt','0x25'],
	'ori'   : ['0x0D','rs','rt','imm'],
    'sb'    : ['0x28','rs','rt','imm'],
    'sh'    : ['0x29','rs','rt','imm'],
    'sll'   : ['0x00','rs','rt','rd','shamt','0x00'],
    'sllv'  : ['0x00','rs','rt','rd','shamt','0x04'],
	'slt'   : ['0x00','rs','rt','rd','shamt','0x2A'],
	'slti'  : ['0x0A','rs','rt','imm'],
    'sltiu' : ['0x0B','rs','rt','imm'],
	'sltu'  : ['0x00','rs','rt','rd','shamt','0x2B'],
	'sra'   : ['0x00','rs','rt','rd','shamt','0x03'],
    'srav'  : ['0x00','rs','rt','rd','shamt','0x07'],
    'srl'   : ['0x00','rs','rt','rd','shamt','0x02'],
    'srlv'  : ['0x00','rs','rt','rd','shamt','0x06'],
    'subu'  : ['0x00','rs','rt','rd','shamt','0x23'],
    'sw'    : ['0x2B','rs','rt','imm'],
	'xor'   : ['0x00','rs','rt','rd','shamt','0x06'],
    'xori'  : ['0x0E','rs','rt','imm']
}

class assembly_parser(object):
    